services:
  nginx:
    container_name: cinema_management_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cinema_management
    depends_on:
      - php
    extra_hosts:
      - "api.cinema:host-gateway"
  php:
    container_name: cinema_management_php
    build: ./images/php81fpm
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - cinema_management
    depends_on:
      - mysql
    extra_hosts:
      - "api.cinema:host-gateway"
  mysql:
    container_name: cinema_management_mysql
    image: mysql:latest
    volumes:
      - ./www:/var/www
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d 
    environment:
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii
      - MYSQL_ROOT_PASSWORD=yii
      - MYSQL_DATABASE=cinema_management
    # command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - cinema_management
  phpmyadmin:
    container_name: cinema_management_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - cinema_management

networks:
  cinema_management:


volumes:
  db:
