services:
  nginx:
    container_name: cinema_managment_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cinema_managment
    depends_on:
      - php
  php:
    container_name: cinema_managment_php
    build: ./images/php81fpm
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - cinema_managment
    depends_on:
      - mysql
  mysql:
    container_name: cinema_managment_mysql
    image: mysql:latest
    volumes:
      - ./www:/var/www
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii
      - MYSQL_ROOT_PASSWORD=yii
      - MYSQL_DATABASE=cinema_managment
    # command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - cinema_managment
  phpmyadmin:
    container_name: cinema_managment_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - cinema_managment
      

networks:
  cinema_managment:

volumes:
  db: